### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by Luzifer3012**
Added german texts and modified existing one for grammar.
To write english is no simple, to translate it it is ;D

### CODE REVIEW

**Comment by Luzifer3012** [comment]
I'm a german native speaker. Some words have small initial letter, but some of them are big in the german language. From un1versal they were written small, but this is false. I also added some translations to the file.

**Comment by driet** [comment]
Yeah, the fix kinda broke it. Native german here, too. Thanks for your work.

**Comment by Luzifer3012** [comment]
Ah thanks! :D
Today i found out that Chorus has Version 2. And then i thougt to correct some small bugs :)

**Comment by driet** [comment]
Maybe they'll just reverse the "fix" and then we'll add the new translations. I think ' in the translation has to be masked like \' ?

**Comment by un1versal** [comment]
This is the right way to fix the issue caused.

@jez500 please just merge this.

**Comment by un1versal** [comment]
@driet now you can add your own fixes ontop, should be easy. if you need help with git let me know.

**Comment by driet** [comment]
Thanks, will do!

**Pull request merged**
