### PR TITLE
missed strings

### PR DESCRIPTION
**Pull request by un1versal**
Some strings that werent found in po files.

I tried installing the bundler and npm in my linux environment but after fighting with ffi for 2 hours I gave up never to try again. hate ruby now. :skull:

### CODE REVIEW

**Comment by jez500** [comment]
Restructured lang folder last release so need to rebase this off master.

ruby/bundler/sass are only used for css/styles so if doing languages, you could get away with `sudo npm install` then `grunt lang` to update the language files.

**Comment by un1versal** [comment]
> Restructured lang folder last release so need to rebase this off master.

done

> ruby/bundler/sass are only used for css/styles so if doing languages, you could get away with sudo npm install then grunt lang to update the language files.

The issue was, installing ffi failed and no matter what I did worked in any way possible, ffi is required apparently, no idea, I gave up, Ill try that but tbh Ive no patience to fight with those things.

**Comment by jez500** [comment]
What is ffi?

**Comment by un1versal** [comment]
no idea, it something that gets pulled in when running install bundler.

**Comment by jez500** [comment]
skip the bundle install step and only install npm modules:
Install: `sudo npm install`
Run: 'grunt lang'

**Comment by un1versal** [comment]
great, any chnaces of a 2.0.9 ;)

**Pull request merged**
