### PR TITLE
Reverse proxy and kodi/addons/webinterface support.

### PR DESCRIPTION
**Pull request by mizaki**
This fixes the http://<kodi>/addons/<web interface> not working and hopefully adds support for reverse proxying. I don't use reverse proxy myself but I believe it should work.

I've not done anything for websockets as it's possible to enter the "host" and because they operate on a different port.

I've left the end point tags in as it's nice to see what is requesting what but I can remove them.

How does it look?

### CODE REVIEW

**Comment by jez500** [comment]
Hi @mizaki, nice work!
I am thinking that as it is called a number of times, it should probably be abstracted into a helper so if there are future changes or tweaks, it is just done in the one place.

eg:
```javascript
helpers.url.baseKodiUrl = (endpoint = '', query = '') ->
  path = endpoint + '?' + query
  if config.get 'static', 'reverseProxy' then 
    path
  else
    '/' + path
```

**Comment by mizaki** [comment]
It seems as if the endpoint option is redundant as it can't be changed, even in advanced settings: http://kodi.wiki/view/Advancedsettings.xml#jsonrpc unless it's undocumented?
Websocket port can be though so, remove endpoint and add websocket port? New PR or roll it in this?

**Comment by jez500** [comment]
Good point, I guess I just had that their if you wanted to add the / in front but reverse proxy takes care of that. Yeah swap endpoint for websocket port as an editable setting, but leave endpoint as a static setting just in case one day it changed (very unlikely).  Just re-roll this one.

Q. Why have you got a query on the endpoint? is it to prevent browser caching? I haven't had any issues with caching and the same endpoint is constantly returning different data (eg. via a colllection).  I think that could probably be omitted.

**Comment by mizaki** [comment]
The ?Kodi, ?Model, etc? That was just so I could see which was being used. They do nothing really and are just ignored. Could leave them in as they might prove useful later?

**Comment by mizaki** [comment]
How's that? Images is a special case so I didn't use the helper. It's already a kind of helper on it's own anyway.

**Comment by jez500** [comment]
Looking good! Thanks @mizaki :)

**Comment by christianprescott** [comment]
Obviously I'm way late to this but...

I do use a reverse proxy and was wondering what the reasoning is behind the option to enable it? It works just fine, but would be really nice if it wasn't necessary to visit settings to switch it on every time I open a fresh browser. I was under the impression it was best practice to use paths without the leading `/` anyway. Is there some benefit to using absolute paths by default?

**Pull request merged**
