### PR TITLE
String updates 2.0.9 and rebuild

### PR DESCRIPTION
**Pull request by un1versal**
Here is a rebuild including #63 and #64

I finally managed to install grunt and the required dependencies, your commands suggestions are far far far from what required to setup the build environment in Linux, as they will always fail.

More or less the what worked here 14.04LTS is: (idk if I missed a step as this was really frustrating)

    sudo apt-get install npm -y
    sudo npm install bundle grunt ffi ruby compass

then when running grunt you get ```error "/usr/bin/env: node: No such file or directory" ``` do:

     sudo ln -s /usr/bin/nodejs /usr/bin/node

Then finally run ```grunt build --force```

### CODE REVIEW

**Comment by jez500** [comment]
Sweet, now you're over that hump it is easy! After pulling future updates do a `sudo npm update; sudo bundle update` to make sure you are up to date with build tools.

btw. what fails of you don't use force on grunt build? Also you can just do `grunt lang` to do [languages only](https://github.com/jez500/chorus2/tree/master/src/lang)

**Comment by un1versal** [comment]
```bash
un1versal@un1versal:~/Desktop/chorus2(master)$ grunt build
Running "po2json:all" (po2json) task
File "dist/lang/_strings/de.json" created.
File "dist/lang/_strings/en.json" created.
File "dist/lang/_strings/fr.json" created.
File "dist/lang/_strings/gr.json" created.
File "dist/lang/_strings/nl.json" created.

Running "copy:lang" (copy) task
Copied 3 files

Running "marked:dist" (marked) task
>> 5 files created.

Running "eco:app" (eco) task
File dist/js/tpl.js created.

Running "coffee:files" (coffee) task
>> 1 files created.

Running "concat:dist" (concat) task
File "dist/js/kodi-webinterface.js" created.

Running "uglify:dist" (uglify) task
File "dist/js/kodi-webinterface.min.js" created.

Running "compass:dist" (compass) task
bundler: command not found: compass
Install missing gem executables with `bundle install`
Warning: You need to have Ruby and Compass installed and in your system PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-compass Use --force to continue.

Aborted due to warnings.
```

Running ```grunt build --force ```fixes that last warning/abort, even though these two are installed. Like I said, Setting up the build environment for chrous2 is the most frustrating Linux task for the last 5 years. tbh I dont care about the --force.

**Comment by jez500** [comment]
Thats cool, it is only skipping the styles, as long as you are not doing anything with css/sass it is fine. As it says, a `bundle install` might help. 

I know it can be a pain getting node/npm/ruby setup but it is well worth it.

**Comment by un1versal** [comment]
for the last time...

###  ```bundle install``` command fails 100% at ffi install

also I get this message when updating packages

```
npm WARN package.json kodi-webinterface@2.0.8 No repository field.
npm WARN package.json bundle@0.2.3 No repository field.
npm WARN package.json nodejs@0.0.0 No repository field.
```

**Comment by jez500** [comment]
ok, ok :)

Those npm WARN are safe to ignore

**Comment by un1versal** [comment]
fyi ffi is a nodejs dependency apparently.

**Pull request merged**
