### PR TITLE
string fixes

### PR DESCRIPTION
**Pull request by un1versal**
Cant remember anymore which source files need fixing so only done the po files, is this right?

### CODE REVIEW

**Comment by jez500** [comment]
looks right to me ;)

**Comment by un1versal** [comment]
I dindt update the ones in dist folder though or the zip file, want me to do that also?

**Comment by jez500** [comment]
Nah, all good, that gets done automatically during a build

**Comment by un1versal** [comment]
well youll need to kick one off then else its outdated :)

**Pull request merged**
