### PR TITLE
fix typo Rquequest -> request (again) 

### PR DESCRIPTION
**Pull request by uNiversaI**
Im pretty sure I fixed this in https://github.com/uNiversaI/chorus2/commit/1e233cada3e38bb1344fd32d76bea9a9923edafa

So please check your internal build scripts or if not a typo let me know :)

### CODE REVIEW

**Comment by jez500** [comment]
Hi @uNiversaI just had a look at uNiversaI@1e233ca and it looks like you only corrected it the compiled js, so next time it build we lost the change. This one will sort it for next build.  Thanks!

**Comment by uNiversaI** [comment]
Ah right... haha well ooops.

can you build it again after this and last fix you did? thank you.

**Comment by jez500** [comment]
@uNiversaI I have update the build with this and #32

**Comment by uNiversaI** [comment]
Thank you all loading up ok... and more issues found this and 32 are fixed now though so good job there.

**Pull request merged**
