### PR TITLE
Fix bad camel case/grammar

### PR DESCRIPTION
**Pull request by uNiversaI**
@jez500

Did something similar to Kodi main English language file not long ago, so I thought these fixes also be welcome here.

Best review them just in case I missed some or changed something by mistake, you know eyes go cone shaped after 5 minutes.

### CODE REVIEW

**Comment by mizaki** [comment]
Imo titles should be "up case". http://grammar.about.com/od/grammarfaq/f/capitalstitle.htm You are right on "e.g." etc. These should come from the resources/English/strings.po file which does need to be fixed up for consistency. The en.json used by JED is generated from the PO file(s).

The main thing is the JS is actually compiled from the coffee script files by grunt. It took me a little while to get used to it but I'm getting there :)

**Comment by uNiversaI** [comment]
Im sorry, this is not a Magazine article or some Book you talking about.

The corrections are 100% grammatically correct. Kodi itself had all this done already.

Take it or leave it.

**Comment by jez500** [comment]
Thanks @uNiversaI 
Yeah don't bother fixing any JS/CSS files as they are all either libraries or will get replaced next time a build runs.
.coffee will get built into js
.eco will get built into js templates
.po will get built into .json 

Side note, grunt is pretty awesome, highly recommend having a play with it. But it is a bit of a learning curve. Requires nodejs, npm, ruby & bundler installed on your system but once you have done that, simply running `npm install` & `bundle install` installs all the dependencies, then running `grunt` does  a build.

**Comment by uNiversaI** [comment]
Thanks, for that explanation which files build which files.

Ill be looking forward to a newer build, and a few more bugs gone ;) great work there jez500. Im a fan.

**Comment by uNiversaI** [comment]
@jez500 When you have a minute would be nice to get a fresher build.

**Pull request merged**
